// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk8NU-6wSqL-sc2oF_Y1l89PTbzAQIRuY',
    appId: '1:1000992719491:web:70c8a9cecdb392131f51b6',
    messagingSenderId: '1000992719491',
    projectId: 'bodyecho-40265',
    authDomain: 'bodyecho-40265.firebaseapp.com',
    storageBucket: 'bodyecho-40265.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK54DKWNzTQMQk0xY8AKfEOadXClPbfi4',
    appId: '1:1000992719491:android:23d249f242296c791f51b6',
    messagingSenderId: '1000992719491',
    projectId: 'bodyecho-40265',
    storageBucket: 'bodyecho-40265.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtz_0vaPYogwEzHxDrV5m0kDlmGayqHVs',
    appId: '1:1000992719491:ios:ca8b646e550b2e7d1f51b6',
    messagingSenderId: '1000992719491',
    projectId: 'bodyecho-40265',
    storageBucket: 'bodyecho-40265.firebasestorage.app',
    iosBundleId: 'com.melih.bodyecho',
  );
}
